apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: direct-image
  annotations:
    run.googleapis.com/launch-stage: BETA
  labels:
    cloud.googleapis.com/location: "us-central1"
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/network-interfaces: '[{"network" : "default" ,"subnetwork" : "default" ,"tags" :[ "guru-1", "guru-2" ]}]'
        run.googleapis.com/vpc-access-egress: "private-ranges-only"
    spec:
      containers:
      - image: nginx
        ports:
        - name: http1
          containerPort: 80
